project:
    type: website
    output-dir: _site
    execute-dir: project
    render:
        - "*.Rmd"
        - "*.md"
        - "*.qmd"
    post-render:
        - touch _site/.nojekyll

website:
    title: "Data Infrastructure Framework Project"
    description: |
        Application to the Novo Nordisk Foundation Data Science Research Infrastructure grant.
    # apple-touch-icon: "images/apple-touch-icon.png"
    # apple-touch-icon-size: 180
    # favicon: "images/favicon.ico"
    site-url: "https://steno-aarhus.github.io/dif-project/"
    repo-url: "https://github.com/steno-aarhus/dif-project"
    repo-branch: main
    repo-actions: [edit, issue, source]
    search:
        location: navbar
        type: overlay
    page-footer:
        center:
            - text: "License under CC-BY 4.0"
              href: LICENSE.md
    navbar:
        left:
            - text: "Community"
              href: community/contribute/index.md
            - text: "About"
              href: about/index.md
        right:
            - icon: "globe"
              href: "https://www.stenoaarhus.dk/research"
            - icon: "twitter"
              href: "https://twitter.com/StenoAarhusRes"
    sidebar:
        - id: community
          title: "Community"
          style: "floating"
          align: left
          contents:
            - community/contribute/index.md
            - section: "Team"
              contents:
                - "community/contribute/team/events.md"
        - id: about
          title: "About"
          contents:
            - about/index.md
            - text: "Mission"
              href: about/mission.md


bibliography: "includes/references.bib"
csl: "includes/vancouver.csl"

format:
  html:
    from: markdown+emoji
    # Not sure this works without R, since it uses the downlit package.
    # code-link: true
    theme:
        - zephyr
        - theme.scss
    toc: true
    toc-location: right
    toc-depth: 3
    # include-before-body:
        # - "includes/site-counter.html"
        # - "includes/contribute.html"

editor:
  mode: visual
