project:
  type: website
  output-dir: _site
  execute-dir: project
  render:
    - "*.Rmd"
    - "*.md"
    - "*.qmd"
  post-render:
    - touch _site/.nojekyll

website:
  title: "seedcase"
  # apple-touch-icon: "images/apple-touch-icon.png"
  # apple-touch-icon-size: 180
  # favicon: "images/favicon.ico"
  site-url: "https://steno-aarhus.github.io/seedcase-project/"
  repo-url: "https://github.com/steno-aarhus/seedcase-project"
  repo-branch: main
  repo-actions: [edit, issue, source]
  search:
    location: navbar
    type: overlay
  page-footer:
    center:
      - text: "License under CC-BY 4.0"
        href: LICENSE.md
  navbar:
    left:
      - text: "Design"
        href: design/index.md
      - text: "Community"
        href: community/contribute/index.md
      - text: "About"
        href: about/index.md
    right:
      - icon: "globe"
        href: "https://www.stenoaarhus.dk/research"
      - icon: "twitter"
        href: "https://twitter.com/StenoAarhusRes"
  sidebar:
    - id: community
      title: "Community"
      style: "floating"
      align: left
      contents:
        - community/contribute/index.md
        - community/posts.md
        - community/CODE_OF_CONDUCT.md
        - section: "Team"
          contents:
            - "community/contribute/team/events.md"
    - id: design
      title: "Design"
      style: "floating"
      align: left
      contents:
      - design/overview.md
      - design/decisions.md
    - id: about
      title: "About"
      contents:
      - about/index.md
      - text: "History"
        href: about/history/index.md
      # - text: "Mission"
      #   href: about/mission.md


bibliography: "includes/references.bib"
csl: "includes/vancouver.csl"

format:
  html:
    from: markdown+emoji
    # Not sure this works without R, since it uses the downlit package.
    # code-link: true
    theme:
      - zephyr
      - theme.scss
    toc: true
    toc-location: right
    toc-depth: 3
    # include-before-body:
      # - "includes/site-counter.html"
      # - "includes/contribute.html"

editor_options:
  markdown:
    wrap: 72
    canonical: true
