project:
    type: website
    output-dir: docs
    execute-dir: project
    render:
        - "*.Rmd"
        - "*.md"
        - "*.qmd"
        - "!resources/instructions.md"
    post-render:
        - touch docs/.nojekyll
    description: |
        Application to the Novo Nordisk Foundation Data Science Research Infrastructure grant.

website:
    title: "Data Infrastructure Framework Project"
    # apple-touch-icon: "images/apple-touch-icon.png"
    # apple-touch-icon-size: 180
    # favicon: "images/favicon.ico"
    site-url: "https://steno-aarhus.github.io/dif-project/"
    repo-url: "https://github.com/steno-aarhus/dif-project"
    repo-branch: main
    repo-actions: [edit, issue, source]
    search:
        location: navbar
        type: overlay
    chapters:
        - index.Rmd
    page-footer:
        center:
            - text: "License under CC-BY 4.0"
              href: LICENSE.md
    navbar:
        left:
            - icon: "globe"
              href: "https://www.stenoaarhus.dk/research"
            - icon: "twitter"
              href: "https://twitter.com/StenoAarhusRes"

bibliography: "resources/references.bib"
csl: "resources/vancouver.csl"

format:
  html:
    from: markdown+emoji
    # Not sure this works without R, since it uses the downlit package.
    # code-link: true
    theme:
        - zephyr
        - theme.scss
    toc: true
    toc-location: left
    toc-depth: 3
    # include-before-body:
        # - "includes/site-counter.html"
        # - "includes/contribute.html"

editor:
  mode: visual
