project:
  type: seedcase-theme
  output-dir: _report


book:
  title: "Seedcase: Software Design and Architecture Documentation"
  output-file: "seedcase-design.pdf"
  chapters:
    - index.qmd
  page-footer:
    center:
      - text: "License: CC-BY 4.0"

bibliography: "includes/references.bib"
csl: "includes/vancouver.csl"

format:
  pdf:
    papersize: a4
    fontsize: 12pt
    geometry:
      - top=30mm
      - bottom=30mm
      - left=30mm
      - right=30mm
    toc: true
    toc-depth: 3

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false

crossref:
  chapters: true
