project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Design"
  site-url: "https://design.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/design"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: LICENSE.md
  page-navigation: true
  navbar:
    pinned: true
    tools:
      - icon: house
        href: "https://seedcase-project.org"
      - icon: github
        href: "https://github.com/seedcase-project/design"
  sidebar:
    pinned: true
    style: "floating"
    contents:
      - index.qmd
      - auto: software/

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
