project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Design"
  site-url: "https://design.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/design"
  page-navigation: true
  navbar:
    title: false
    logo: _extensions/seedcase-project/seedcase-theme/logos/navbar-logo-seedcase-design.svg
    logo-alt: "Seedcase Design logo: Main page"
    pinned: true
    left:
      - text: "Organization"
        href: organisation/index.qmd
      - text: "Software"
        href: software/index.qmd
      - text: "Data"
        href: data/index.qmd
      - text: "Style"
        href: style/index.qmd
      - text: "Accessibility"
        href: accessibility/index.qmd
    tools:
      - icon: house
        href: "https://seedcase-project.org"
        aria-label: "House icon: Seedcase Project home page"
      - icon: github
        href: "https://github.com/seedcase-project/design"
        aria-label: "GitHub icon: Source code"
  sidebar:
    - id: software
      pinned: true
      style: "floating"
      contents:
        - auto: software/
    - id: organization
      contents:
        - organisation/index.qmd
        - organisation/collaboration.qmd
        - organisation/contribution.qmd
    - id: data
      contents:
        - data/index.qmd
    - id: style
      contents:
        - auto: style/
    - id: accessibility
      contents:
        - accessibility/index.qmd

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
