project:
  type: seedcase-theme

website:
  title: "Seedcase Project: Design"
  favicon: "/images/logo.svg"
  site-url: "https://design.seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/design"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: LICENSE.md
  page-navigation: true
  navbar:
    pinned: true
    logo: "/images/logo.svg"
    right:
      - icon: list
        menu:
          - text: "Main"
            href: "https://seedcase-project.org"
    tools:
      - icon: github
        href: "https://github.com/seedcase-project/design"
  sidebar:
    - id: design
      pinned: true
      style: "floating"
      align: left
      collapse-level: 2
      contents:
        - index.qmd
        - auto: software-architecture/

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"
      # - "includes/contribute.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
