project:
  type: seedcase-theme

website:
  title: "Seedcase Project"
  favicon: "/images/logo.png"
  site-url: "https://seedcase-project.org/"
  repo-url: "https://github.com/seedcase-project/seedcase-project"
  page-footer:
    center:
      - text: "License: CC-BY 4.0"
        href: LICENSE.md
  navbar:
    logo: "/images/logo.png"
    right:
      - text: "About"
        href: about/index.md
      - text: "Community"
        href: community/index.qmd
      - text: "Design"
        href: design/index.md
      - icon: github
        href: "https://github.com/seedcase-project/seedcase-project"
  sidebar:
    - id: community
      title: "Community"
      style: "floating"
      align: left
      contents:
        - community/index.qmd
        - community/posts.md
        - community/CONTRIBUTING.md
        - community/blocks.qmd
        - community/roadmap.qmd
        - community/decisions.md
        - community/CODE_OF_CONDUCT.md
    - id: design
      title: "Design"
      style: "floating"
      align: left
      contents:
        - design/index.md
        - section: "Software Architecture Documentation"
          contents:
            - design/software-architecture/introduction.qmd
            - design/software-architecture/constraints.qmd
            - design/software-architecture/context.qmd
            - design/software-architecture/solution-strategy.qmd
            - design/software-architecture/building-block-view.qmd
            - design/software-architecture/runtime-view.qmd
            # - design/software-architecture/deployment-view.qmd
            - design/software-architecture/cross-cutting-concepts.qmd
            # - design/software-architecture/architecture-decisions.qmd
            # - design/software-architecture/quality-requirements.qmd
            - design/software-architecture/risks.qmd
        - design/decisions.md
    - id: about
      title: "About"
      contents:
      - about/index.md
      - text: "History"
        href: about/history/index.md
      # - text: "Mission"
      #   href: about/mission.md


bibliography: "includes/references.bib"

# format:
#   seedcase-theme-html:
    # include-before-body:
      # - "includes/site-counter.html"
      # - "includes/contribute.html"

editor:
  markdown:
    wrap: 72
    canonical: true

execute:
  echo: false
