---
title: "Style guidelines"
---

{{< include /includes/_wip.qmd >}}

## Purpose

These documents contained within the style section are meant to provide
guidance on how to write, format, and structure documents within the
Seedcase Project. They are meant to be a guide and a reference for all
team members and contributors to make sure that we have some consistency
in development, coding, and writing across all Seedcase documentation
and software.

We assume the reader is either:

-   A new team member who uses these style documents as onboarding
    material.
-   A current team member who needs to reference the style documents for
    a specific task or as a reminder.
-   A potential or current contributor who wants to understand how we
    work and how to best contribute.
-   Other groups who want to use these documents as inspiration or to
    copy/modify for their own uses.

## General principles

Following with our Seedcase Project
[principles](https://seedcase-project.org/about/principles) to use
established standards and conventions, the general principle for styling
is to use existing guides. There exists several style guides and
resources for structuring code and doing software development, below are
specific guides we make use of:

### Python

-   [PEP 8](https://peps.python.org/pep-0008/): The official style guide
    for writing Python.
-   [Google Style
    Guide](https://google.github.io/styleguide/pyguide.html): Google's
    Python style guide.
-   [Hitchhiker's Guide to Python](https://docs.python-guide.org/): A
    guide to best practices for writing Python code.
