---
title: "Constraints"
order: 2
---

{{< include /includes/_wip.qmd >}}

This document lists organizational and political/legal constraints
that we must consider when developing software for the Seedcase Project.

The main "philosophical" and value-based constraints are described in
the [Values and principles](principles.qmd) section.
These form the basis for all other decisions and designs. Some of those
constraints are summarized below.

## Organizational constraints

| Constraints                     | Background/Motivation                                                                                   |
|------------------|------------------------------------------------------|
| Time schedule                   | Funding is until end of \~2027                                                                          |
| Resources                       | Currently only have a fixed set of funds                                                                |
| Small team                      | Only have 4-5 people on team, \~3 who are full-time                                                     |
| Limited knowledge/skill support | Data/software engineering is not common in research environments, so local knowledge/skills are limited |

: Organizational constraints we need to consider for Seedcase software.

## Political/legal constraints

| Constraints                        | Background/Motivation                                                                       |
|---------------------|---------------------------------------------------|
| Use open source license            | For both practical and philosophical reasons, we will license Seedcase with an open license |
| Need endorsement from legal and IT | They have broad institutional influence, so at least having some support is vital           |

: Political/legal constraints we need to consider for Seedcase software.
