---
title: Introduction
order: 1
---

{{< include /includes/_wip.qmd >}}

Seedcase was born out of a desire to bring modern data engineering
practices, technologies, and processes to research environments.
Technological and computing skills and knowledge within health research
(at least in our experience) often lags far behind what is the current
state-of-the-art. The connected design documents describe the
architecture of Seedcase software as well as the underlying data
architecture that Seedcase software implements as a framework. Our
specific goals for the Seedcase Project are:

<!--TODO removed something here, now the colon is hanging-->

The framework acts as an (open source) starting template for setting up
data infrastructures that follow principles and requirements listed
below. *Framework* here is defined as: 1) a bundled or recommended set
of software programs; 2) a defined and standardized set of conventions
on the structure and format of the filesystem, URL paths, and API calls;
and, 3) a defined and standardized structure to the data and associated
documentation, all of which are linked together as modular components.

The Community based aims are covered more in our [Community
site](https://community.seedcase-project.org) page. While these aims are
not related to the software itself, it does impact architectural and
design decisions we make.

## Requirements Overview

Primary **goals** of Seedcase software are:

1.  **Ingesting data and metadata into standardized storage**: Take
    generated data from source locations (such as the clinic or
    laboratories) that may be distributed geographically or
    organizationally and store it in a secure, centralized location in a
    standardized and efficient format to form a Data Resource. Metadata
    are similarly stored and linked to the data.
2.  **Showcasing data and metadata for discoverability and data access
    requests**: Take stored metadata as well as some basic descriptive
    information of the data inside the Data Resource and display them on
    a web portal as a list. Users can select specific data they are
    interested in from the list and submit a request to use these data.
    These requests for data are saved and stored in the backend.
3.  **Tracking data projects using the data for managing and auditing**:
    The stored requests for data are displayed for admin users to
    approve of (or not). Approved requests get converted to ongoing data
    projects, which are displayed on the web portal.

While the software architecture documentation largely encompasses the
software and data components of the Seedcase Project, because of our
secondary aims (to create a framework that other research groups and
companies can relatively easily implement, and modify, for their own
purposes), we need to describe additional requirements that aren't
strictly technical. We'll cover some Guiding Principles we need to
follow for the Seedcase Project, describe our target users and
use-cases, and then list the main functionalities of the Seedcase
framework.

### Users

The Seedcase framework is developed and designed with four users and
their associated use cases in mind. These four users we've translated into user roles, which are described
in more detail on the [User Requirements](user-requirements.qmd) page,
are:

1.  **Data Contributor**: inputs data to the Data Resource, e.g.,
    authorized centers and researchers.
2.  **Data Requester**: requests access to a subset of data in the Data
    Resource, e.g., researchers and clinicians.
3.  **Administrator**: manages the Data Resource. Data controllers, as
    defined by the GDPR, fall into this category.
4.  **External User**: views updates on findings and results from the
    Data Resource such as aggregate statistics, e.g., policymakers,
    healthcare workers, journalists, researchers, and the general
    public.

### Main functionality

-   **One Data Resource per Seedcase "instance"**: For users with
    multiple Data Resources, each Data Resource will be housed in a
    separate "instance" of the infrastructure framework.
-   **Upload or update data**: Input data into the Data Resource in
    batches or continuously into the backend storage, either into the
    database or as raw data files.
-   **Upload or update metadata**: When inputting data, attach metadata
    along side it.
-   **Store changes to the data in a changelog**: Track and list changes
    made to the data within the Data Resource for auditing and
    recordkeeping.
-   **Display metadata and basic information on the data in the Data
    Resource on a user interface**: So external users and users
    interested in data in the Data Resource can browse what is
    available.
-   **Provide a data access submission process**: Allow users to submit
    a data access request for data in the Data Resource, along with a
    data selection process (for instance, like a shopping cart). Submit
    a request for access as a data project that includes selected data
    and a brief reason as
-   **Store data request submissions as data projects for auditing and
    managing**: Save submissions as "data projects", where admin users
    can approve (or decline) these data projects and manage whether they
    are "ongoing", "completed", or "declined". The stored ongoing or
    completed data projects will be displayed on the web portal for
    discoverability and transparency on the subset of the Data Resource
    used.
-   **Allow for individual parts to be independently installable and
    usable**: Users might not need or want some of the functionality, so
    being able to have individual and independent parts that are usable
    on their own is necessary. These independent parts also need to be
    able to connect and work together.

## Quality Goals

We will go into more detail on the quality goals in the [Quality
requirements](quality-requirements.qmd) section, but here is a brief
overview of the quality goals we have for Seedcase software:

| Goals                                       | Scenarios                                                                                                       |
|--------------------|----------------------------------------------------|
| Beginner-friendly interfaces                | We want non-technical users to use this, therefore it should be easy to learn and use.                          |
| Comprehensive functionality and easy to use | All apps under the Seedcase banner should be able to do what we need them to do, with ease.                     |
| Reliable and robust                         | As much as possible we want to simplify the applications and ensure that there is comprehensive error handling. |
| Secure and legally compliant                | Seedcase software currently targets health data, so it needs to be compliant with privacy and security laws.    |

## Stakeholders

This section contains an explicit list of those who will need, use, or
review the design documentation. This is the "audience" or readers of
these documents. Specifically it is anyone who:

-   Should know the architecture
-   Have to be convinced of the architecture
-   Have to work with the architecture or the code
-   Need the documentation of the architecture for their work
-   Have to come up with decisions about the system or its development

Currently, we've identified these stakeholders along with some
expectations we believe they have for these documents.

-   **Developers/contributors**: Either core developer or external
    contributor, who use these documents to better understand what needs
    to be done and why things were done the way they are. They will read
    it for general and technical reasons.

-   **Key partners ([DD2](https://dd2.dk/),
    [SDCA](https://www.stenoaarhus.dk/))**: They were co-applicants for
    the funding and will be the first users (and testers) of Seedcase
    software. They will likely review the overview sections and
    higher-level diagrams for general understanding, rather than for
    technical purposes.

-   **External reviewers**: Part of our plan is to send this document to
    a software consultancy firm to critically review it and provide
    feedback on it. This will ensure that we do not miss anything
    important or critical. These reviewers will read these documents
    critically from a technical perspective.

-   **Funder (Novo Nordisk Foundation)**: We need to send progress
    reports to our funders. They will likely use them for
    record-keeping, accountability, and auditing purposes.

-   **Data owners/generators (users of the software)**: These may
    include study coordinators or principal investigators of studies who
    will or have generated data and who are looking for solutions to
    store and share their data. They will likely read this document from
    a high-level, such as the overview sections and diagrams, to assess
    if it fits their needs.

-   **Interested researchers**: Researchers whose duties include
    research software or data engineering may be interested in the
    technical side of the Seedcase Project, either to become a
    contributor or to modify for their own purposes.

-   **Institutional admin/IT**: Building Seedcase software will not be
    enough to get researchers using it. We also have to ensure that we
    have institutional IT on board and see that Seedcase software fits
    legal, privacy, and security concerns they may have.
