---
title: "Runtime view"
order: 6
---

This section describes the concrete behaviour, interactions, and
pathways that data take within the Seedcase framework. "Runtime" in this
case refers to how the software works "in action".

## Data input

<!-- TODO: Insert link to sprout/runtime-view#data-input -->

For a detailed description of the expected types of input data and the
different ways users can upload data to the Seedcase framework, see the
[Data Input](https://sprout.seedcase-project.org/docs/design/runtime-view#data-input) section.

## Requesting data

There are two main ways to request for data from a Data Resource managed
by Seedcase:

1.  Submitting an application to request data, which will create a new
    data project.
2.  Re-using parts of an existing data project.

![Logged in user who is requesting data from a Data Resource. <br> The
"alt" box shows the alternative workflows depending on whether the user
requests a new data projects or re-uses an existing data project for the
request.](../images/runtime-data-request.svg){#fig-data-request}

### Applying for a new data project

Users who want to request data can browse the metadata, which includes a
list of variables and datasets available as well as a data dictionary
and changelog, in the Seedcase-managed Data Resource. Similar to an
online shopping cart, users who want specific variables in the Data
Resource will be able to select them from the list of variables. These
selected variables will go into the request application as a new data
project, which would be used to automate the data extraction process. In
order to add the variables to a new data project application, the user
would have to be registered and logged in.

Aside from the selected list of requested variables, the user would need
to write some information about the rationale for and intended use of
the data as well as other project-specific metadata.

Admin users would approve any new data project applications. When an
application is approved, it would trigger automated processes to run the
data extraction and subsetting process. It would also bundle it and
prepare it for transfer to the applicant user's secure server or other
location where the data will be stored. Admin users can also modify the
application form to comply with local regulations and legal
requirements, such as removing or adding variables (apart from the
variable list), that may be required.

The user can update the data project at any point in the data project's
life-cycle. This includes requesting more variables or modifying the
data project description and aim. The admin users would then need to
approve these updates.

### Re-using an existing data project

Because data projects are stored (and optionally displayed on the Web
Portal) as JSON or other machine-readable format, users who want to copy
and modify an existing data project can extract and use the details from
that project as part of a new data project. The data projects listing on
the Web Portal will include a button to either download the JSON
metadata or to copy the project into a new data project application.

## Browsing projects and results

There are at least three routes, we anticipate the [External
User](user-requirements.qmd#roles-and-use-cases) might take when
browsing the Data Resource:

1.  Reading about the Data Resource, its history, organizational
    structure and ownership, and any other details in a typical "About"
    section.
2.  Browsing the completed and ongoing projects that are using or have
    used the Data Resource, including viewing some of the basic results
    of the completed projects.
3.  Viewing some basic aggregate statistics of some key variables in the
    Data Resource. The aggregate statistics would be generated
    programmatically.
