@startuml c4-container
!theme seedcase from https://raw.githubusercontent.com/seedcase-project/seedcase-theme/main
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(adm, "Administrator")
Person(inp, "Data Contributor")
Person(req, "Data Requester")

Person_Ext(ext, "External User")

Container_Boundary(seed, "Seedcase Data Resource", "web-interface") {
	Container(land, "Main Seedcase page", "navigation page", "Main page showing installed apps")
	Container(sec, "User authentication", "interface", "Called when selecting any app which needs security")
	Container(sprout, "Sprout", "web-app", "Uploads the research instance data")
	Container(flower, "Flower", "web-app", "Makes metadata available to browse")
	Container(prop, "Propagate", "web-app", "Allows others to request data\n")
	Container(garden, "Garden", "web-app", "Handles workflow for data requests")
	Container_Boundary(backend, "Data storage"){
  	ContainerDb(data, "Research data", "db, csv, etc")
  	ContainerDb(user, "User data", "db")
	}
}

Lay_U(garden, land)
Lay_U(prop, land)
Lay_Left(data, user)
Lay_Right(sprout, flower)
Lay_Right(flower, prop)
Lay_Right(prop, garden)

Rel(inp, land, "")
Rel(req, land, "")
Rel(adm, land, "")
Rel(ext, land, "")
BiRel_Left(land, sec, "")
Rel(land, sprout, "")
Rel(land, garden, "")
Rel(land, prop, "")
Rel(land, flower, "")
Rel_U(data, flower, "")
Rel_U(data, garden, "")
Rel_U(data, prop, "")
BiRel(sprout, data, "")
BiRel(sec, user, "")

SHOW_LEGEND()

@enduml
