@startuml C4-Container
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

HIDE_STEREOTYPE()

Container(seed, "Main Seedcase", "web-interface")
Container(sec, "User Authentication", "interface", "called when selecting any app which needs security")
Container(sprout, "Sprout", "web-app", "uploads the research instance data")
Container(garden, "Garden", "web-app")
Container(prop, "Propagate", "web-app")
Container(flower, "Flower", "web-app")
Container_Boundary(backend, "databases"){
  ContainerDb(data, "Research Data")
  ContainerDb(user, "User Data")
}

Lay_Left(data, user)

BiRel_Left(seed, sec, "")
Rel(seed, sprout, "")
Rel(seed, garden, "")
Rel(seed, prop, "")
Rel(seed, flower, "")
BiRel(sprout, data, "")
BiRel(sec, user, "")
@enduml
