@startuml High_level
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(user_input, "Data input")
Person(user_request, "Data discover and request")
Person(user_admin, "Admin", "Data controllers or data managers")

Person_Ext(user_results, "Explore findings and projects")

Lay_R(user_admin, user_input)
Lay_R(user_input, user_results)
Lay_R(user_results, user_request)


AddRelTag("line", $lineStyle = DashedLine())

System(ui, "Data Resource structured by Seedcase")
System_Ext(external_server, "External secure server")

Rel(user_input, ui, "Uploads data")
Rel(user_request, ui, "Find and request data for project")
Rel(user_admin, ui, "Manages issues and requests for data projects")
Rel(user_results, ui, "Explore findings of study")
Rel(user_results, user_request, "May become", $tags="line")

Rel_Right(ui, external_server, "Data extract for approved data projects")
Rel(user_request, external_server, "Access requested data")
@enduml
