# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  issue_comment:
    types: [created]

name: Commands

jobs:
  reformat_md:
    if: ${{ github.event.issue.pull_request && (github.event.comment.author_association == 'MEMBER' || github.event.comment.author_association == 'OWNER') && startsWith(github.event.comment.body, '/reformat_markdown') }}
    name: reformat_md
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/pr-fetch@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '2.17.1' # The pandoc version to download (if necessary) and use.

      - name: Reformat Markdown files
        run: |
          for file in $(git diff --name-only --relative main... | cat); do
            echo "- The file '$file' was modified in this branch."
            if [[ $file =~ \.[qRr]?md$ ]]; then
              # https://github.com/rstudio/rstudio/blob/4f7063b13bb0bae8377639a36d3ff4b7626de6e3/src/gwt/panmirror/src/editor/src/pandoc/pandoc_converter.ts#L90
              pandoc -f markdown -t markdown -o $file $file
              pandoc $file \
                --to markdown-smart+yaml_metadata_block \
                --from markdown-smart \
                --self-contained \
                --markdown-headings=setext \
                --wrap=auto \
                --columns=72 \
                -o $file
              echo "  - '$file' was reformatted to canonical markdown."
            fi
          done

      - name: Commit
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m 'Reformat Markdown files to standard format'

      - uses: r-lib/actions/pr-push@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
